language: cpp
compiler: gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gfortran-6
env:
  - MATRIX_EVAL="FC=gfortran-6 CC=gcc-6 && CXX=g++-6"
script:
  - mkdir cmake-build && cd cmake-build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DTEST_COVERAGE=ON ../
  - make
before_install:
  - eval "${MATRIX_EVAL}"
after_success:
  - ./suanPan -f ../Example/C3D20.supan > /dev/null
  - ./suanPan -f ../Example/C3D8.supan > /dev/null
  - ./suanPan -f ../Example/COOK.supan > /dev/null
  - ./suanPan -f ../Example/COOK4.supan > /dev/null
  - ./suanPan -f ../Example/CPS3.supan > /dev/null
  - ./suanPan -f ../Example/CPS8.supan > /dev/null
  - ./suanPan -f ../Example/CPS4NL.supan > /dev/null
  - ./suanPan -f ../Example/GQ12.supan > /dev/null
  - ./suanPan -f ../Example/IREGULARBEAM.supan > /dev/null
  - ./suanPan -f ../Example/MACNEAL.supan > /dev/null
  - ./suanPan -f ../Example/PROTO01.supan > /dev/null
  - ./suanPan -f ../Example/QE2.supan > /dev/null
  - ./suanPan -f ../Example/TRUSS2D.supan > /dev/null
  - ./suanPan -f ../Example/LEE.FRAME.supan > /dev/null
  - for SRC in `find . | egrep '\.o'`; do gcov-6 -n $SRC > /dev/null; done
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false