language: cpp
compiler: gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gfortran-6
env:
  - MATRIX_EVAL="FC=gfortran-6 CC=gcc-6 && CXX=g++-6"
script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DTEST_COVERAGE=ON ../
  - make
  - ./suanPan -f ../Example/TEST1.COV
  - ./suanPan -f ../Example/TEST2.COV
  - ./suanPan -f ../Example/TEST3.COV
  - for SRC in `find . | egrep '\.o'`; do gcov-6 -n $SRC; done
before_install:
  - eval "${MATRIX_EVAL}"
after_success: 
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false