dist: precise
language: cpp
compiler: gcc
os: linux
addons:
  apt:
    packages:
      - g++-5
      - gfortran
env:
  - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
script:
  - mkdir cmake-build && cd cmake-build && cmake ../ && make
before_install:
  - eval "${MATRIX_EVAL}"
notifications:
  email: false