language: cpp
compiler: gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gfortran-6
env:
  - MATRIX_EVAL="FC=gfortran-6 CC=gcc-5 && CXX=g++-5"
script:
  - sudo apt-get update -qq
  - mkdir cmake-build && cd cmake-build && cmake ../ && make
before_install:
  - eval "${MATRIX_EVAL}"
notifications:
  email: false