language: cpp
compiler: gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gfortran-6
      - lcov
env:
  - MATRIX_EVAL="FC=gfortran-6 CC=gcc-6 && CXX=g++-6"
script:
  - mkdir cmake-build && cd cmake-build && cmake -DCMAKE_BUILD_TYPE=Debug ../ && make
  - ./conv.sh
before_install:
  - eval "${MATRIX_EVAL}"
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false