language: cpp
compiler: gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
env:
  - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
script:
  - mkdir cmake-build && cd cmake-build && cmake ../ && make
before_install:
  - eval "${MATRIX_EVAL}"