language: generic
compiler: gcc-6
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gfortran-6
env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
script:
  - mkdir cmake-build && cd cmake-build && cmake ../ && make
before_install:
  - eval "${MATRIX_EVAL}"
notifications:
  email: false